# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./crm7:/var/www/html/

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #     - ./db:/mnt/db/

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

# volumes:
#   mysql-data:
